Add rancher-desktop workflow to main

diff --git a/.github/workflows/test-main.yml b/.github/workflows/test-main.yml
--- a/.github/workflows/test-main.yml
+++ b/.github/workflows/test-main.yml
@@ -130,6 +130,86 @@ jobs:
       - name: Run tests
         run: npm run test:ci -- generic-container.test.ts
 
+  rancher-desktop:
+    runs-on: ${{ matrix.os-version }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os-version: [ macos-latest ]
+        node-version: [ 14.x, 16.x, 18.x ]
+    steps:
+      - name: Code checkout
+        uses: actions/checkout@v3
+      - name: Setup Rancher Desktop
+        run: |
+          brew install docker docker-compose
+          brew install --cask rancher
+          
+          TIMEOUT_SECS_USER_DIR=60
+          TIMEOUT_SECS_USER_SOCKET=300
+          
+          echo "Open Rancher Desktop app"
+          open "/Applications/Rancher Desktop.app"
+          
+          echo "Wait max of ${TIMEOUT_SECS_USER_DIR}s for Rancher Desktop to create user directory"
+          for i in $(seq 1 ${TIMEOUT_SECS_USER_DIR}); do
+              if [ -d "$HOME/.rd" ]; then
+                echo "Rancher Desktop user directory created after ${i}s"
+                break
+              fi
+              sleep 1
+          done
+          
+          if [ ! -d "$HOME/.rd" ]; then
+            echo "Rancher Desktop user directory not found"
+            exit 1
+          fi
+          
+          echo "Rancher Desktop initialised successfully, now configure the container runtime"
+          $HOME/.rd/bin/rdctl set \
+            --container-engine.name=moby \
+            --application.admin-access=false \
+            --kubernetes.enabled=false \
+            --application.start-in-background=true \
+            --application.path-management-strategy=manual \
+            --virtual-machine.number-cpus=3 \
+            --virtual-machine.memory-in-gb=14 \
+            || true
+          
+          echo "Restart Rancher Desktop"
+          $HOME/.rd/bin/rdctl shutdown
+          $HOME/.rd/bin/rdctl start
+          
+          echo "Wait max of ${TIMEOUT_SECS_USER_SOCKET}s for Rancher socket"
+          
+          for i in $(seq 1 ${TIMEOUT_SECS_USER_SOCKET}); do
+              if [ -e "$HOME/.rd/docker.sock" ]; then
+                echo "Rancher Desktop socket created after ${i}s"
+                break
+              fi
+              sleep 1
+          done
+          
+          if [ ! -e "$HOME/.rd/docker.sock" ]; then
+            echo "Rancher Desktop socket not found"
+            exit 1
+          fi
+          
+          echo "{}" > $HOME/.docker/config.json
+      - name: Set environment
+        run: |
+          echo "DOCKER_HOST=unix://${HOME}/.rd/docker.sock" >> $GITHUB_ENV
+          echo "TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock" >> $GITHUB_ENV
+          echo "NODE_OPTIONS=--dns-result-order=ipv4first" >> $GITHUB_ENV
+      - name: Install NodeJS ${{ matrix.node-version }}
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+      - name: Install dependencies
+        run: npm ci --omit=optional
+      - name: Run tests
+        run: npm run test:ci -- generic-container.test.ts
+
   smoke-test:
     runs-on: ${{ matrix.os-version }}
     strategy:
